# Generated by Django 2.2.7 on 2020-03-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=200)),
                ('Cv', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('website', models.BooleanField(max_length=200)),
            ],
        ),
    ]
