# Generated by Django 2.2.7 on 2020-03-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storedetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='website',
            field=models.CharField(max_length=200),
        ),
    ]
